name: CI Post Comment
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  post-comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download code-coverage-results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
